---
driver:
  name: docker
provisioner:
  name: chef_zero
verifier:
  name: inspec
  format: junit
  output: ./inspec_output.xml
platforms:
  - name: ubuntu
    driver_config:
      gui: true
suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[Resume::resume]
    attributes:
