---
driver:
  name: vagrant
provisioner:
  name: chef_zero
verifier:
  name: inspec
platforms:
  - name: ubuntu/trusty64
    driver_config:
      gui: true
suites:
  - name: default
    run_list:
      - recipe[Resume::default]
    attributes:
