name 'Resume'
maintainer 'John Kerry'
maintainer_email 'john@kerryhouse.net'
license 'all_rights'
description 'Builds a resume with obscured personal information'
long_description 'Builds a resume with obscured personal information'
version '0.1.0'

depends 'apt', '~> 3.0.0'
depends 'zipfile', '~> 0.1.0'
